from flask import request, flash, redirect, url_for
from flask_login import login_user
from werkzeug.security import check_password_hash, generate_password_hash

@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        user = User.query.filter_by(username=username).first()
        if user and check_password_hash(user.password_hash, password):
            login_user(user)
            return redirect(url_for('dashboard'))
        flash('Invalid username or password')
    return render_template('login.html')

@app.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        email = request.form.get('email')
        user = User.query.filter_by(username=username).first()
        if user:
            flash('Username already exists')
        else:
            new_user = User(username=username, email=email, password_hash=generate_password_hash(password))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            return redirect(url_for('dashboard'))
    return render_template('register.html')from flask_login import UserMixin

class User(UserMixin, db.Model):
    # ... your fields here ...from flask_login import LoginManager, login_required, current_userfrom flask_login import logout_user

@app.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))@app.route('/dashboard')
@login_required
def dashboard():
    return render_template('dashboard.html')"""Add is_admin column to User model and leader_username to Faction

Revision ID: 01cebf8a5eb8
Revises: 
Create Date: 2024-10-04 20:24:52.830106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01cebf8a5eb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader_username', sa.String(length=64), nullable=True))
        batch_op.drop_constraint('faction_leader_id_fkey', type_='foreignkey')
        batch_op.drop_column('leader_id')

    # Update existing rows with a default value for leader_username
    op.execute("UPDATE faction SET leader_username = 'Unknown Leader' WHERE leader_username IS NULL")

    # Make leader_username non-nullable
    with op.batch_alter_table('faction', schema=None) as batch_op:
        batch_op.alter_column('leader_username', nullable=False)

    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.alter_column('kills',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('destroyed_traps',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('lost_associates',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('lost_traps',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('healed_associates',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('wounded_enemy_associates',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('eliminated_enemy_influence',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.alter_column('eliminated_enemy_influence',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('wounded_enemy_associates',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('healed_associates',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('lost_traps',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('lost_associates',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('destroyed_traps',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('kills',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('faction', schema=None) as batch_op:
        batch_op.alter_column('leader_username', nullable=True)
        batch_op.add_column(sa.Column('leader_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('faction_leader_id_fkey', 'user', ['leader_id'], ['id'])
        batch_op.drop_column('leader_username')

    # ### end Alembic commands ###
