"""Add created_at column to User model

Revision ID: 039176608ff6
Revises: 01cebf8a5eb8
Create Date: 2024-10-10 12:07:06.707999

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '039176608ff6'
down_revision = '01cebf8a5eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
